sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /admin

# sonata_user_admin_security_check:
#    path: /admin/login_check
#    controller: App\Controller\LoginController::index
redirect_admin:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: sonata_admin_dashboard
        permanent: false